image: gitpod/workspace-full

tasks:
  - name: Setup Desktop
    init: |
      sudo apt-get update
      sudo apt-get install -y xfce4 xfce4-terminal firefox
    command: |
      vncserver :1 -geometry 1280x800 -depth 24
      websockify --web=/usr/share/novnc/ 6080 localhost:5901

ports:
  - port: 6080
    onOpen: open-preview
